/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Winter Melon
 */

import java.io.*;
import java.net.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class EmployeeListFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeListFrame
     */
    public EmployeeListFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadEmployeeTable();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void loadEmployeeTable() {
    List<String[]> employees = CSVHelper.loadEmployeeData();
    DefaultTableModel model = new DefaultTableModel(){
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
    
    model.setColumnIdentifiers(new String[] {
        "Employee #", "Last Name", "First Name", "SSS #", "PhilHealth #", "TIN #", "Pag-ibig #"
    });

    for (String[] row : employees) {
        model.addRow(new Object[] {
            row[0], row[1], row[2], row[6], row[7], row[8], row[9]
        });
    }

    // Table Variable
    jTable1.setModel(model);
}
          
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnViewEmployee = new javax.swing.JButton();
        btnNewEmployee = new javax.swing.JButton();
        btnModifyEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(8, 168, 138));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewEmployee.setText("View Employee");
        btnViewEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewEmployee.setMaximumSize(new java.awt.Dimension(140, 30));
        btnViewEmployee.setMinimumSize(new java.awt.Dimension(140, 30));
        btnViewEmployee.setPreferredSize(new java.awt.Dimension(140, 30));
        btnViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, -1, -1));

        btnNewEmployee.setText("New Employee");
        btnNewEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewEmployee.setMaximumSize(new java.awt.Dimension(140, 30));
        btnNewEmployee.setMinimumSize(new java.awt.Dimension(140, 30));
        btnNewEmployee.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(btnNewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 149, -1, -1));

        btnModifyEmployee.setText("Modify Employee");
        btnModifyEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModifyEmployee.setMaximumSize(new java.awt.Dimension(140, 30));
        btnModifyEmployee.setMinimumSize(new java.awt.Dimension(140, 30));
        btnModifyEmployee.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(btnModifyEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 197, -1, -1));

        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteEmployee.setMaximumSize(new java.awt.Dimension(140, 30));
        btnDeleteEmployee.setMinimumSize(new java.awt.Dimension(140, 30));
        btnDeleteEmployee.setPreferredSize(new java.awt.Dimension(140, 30));
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 245, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("MotorPH Portal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 36, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/login-bg.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee first.");
            return;
        }

        String employeeId = jTable1.getValueAt(selectedRow, 0).toString();
        new EmployeeDetailsFrame(employeeId).setVisible(true);        
    }//GEN-LAST:event_btnViewEmployeeActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnModifyEmployee;
    private javax.swing.JButton btnNewEmployee;
    private javax.swing.JButton btnViewEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
