
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Winter Melon
 */

import java.util.List;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(String employeeId) {
    initComponents();
    setLocationRelativeTo(null);
    
    String fullName = getEmployeeFullName(employeeId);
    lblFirstMessage.setText("Welcome " + fullName + "!");

}
    
    private String getEmployeeFullName(String employeeId) {
    List<String[]> employees = CSVHelper.loadEmployeeData();
    for (String[] emp : employees) {
        if (emp[0].equals(employeeId)) {
            return emp[2] + " " + emp[1];  // First Name + Last Name
        }
    }
    return "Employee";
}
    
public MainFrame() {
        this("Unknown");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        lblFirstMessage = new javax.swing.JLabel();
        btnViewEmployeeList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/temp-logo2.gif"))); // NOI18N
        getContentPane().add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, -1));

        lblFirstMessage.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblFirstMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstMessage.setText("= Welcome Message =");
        getContentPane().add(lblFirstMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 220, 530, -1));

        btnViewEmployeeList.setText("View Employee List");
        btnViewEmployeeList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnViewEmployeeList.setMaximumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setMinimumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setPreferredSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeListActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEmployeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/login-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeListActionPerformed
        new EmployeeListFrame().setVisible(true);
    }//GEN-LAST:event_btnViewEmployeeListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewEmployeeList;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFirstMessage;
    // End of variables declaration//GEN-END:variables
}
